### ISSUE TITLE
[CustomFields] Add custom fields to entity through configuration

### ISSUE THREAD

**Issue by MartinRosserEB** [EmchBerger/cube-common-bundle#13]
User requirement / use case:

- Entity is based on existing entity (e.g. Document or Reservation) but needs project specific adaptations (e.g. Plan-Identifier or various project-specific fields such as TestBench etc.). These project specific adaptations change over time.

Requirements:

- [x] Allow configuring additional fields for an entity
- [x] Additional fields can be of type: free-text (single line), text (text field), select (pre-defined, configured values), date, entity (select referring to other, existing entity)
- [ ] Additional fields may be dependent on each other (mainly select type), with choices dependent on selected parent field choice ➡️ postpone
- [ ] Additional fields may have access rights defined on them (e.g. for select, certain selectable values only available to certain groups / users)
- [x] Additional fields should be populated in index pages of entities to which they are attached
- [ ] Additional fields may be required dependent on status (e.g. when creating a Reservation, only a subset of fields is mandatory; When assigning a reservation to the supplier, more fields are mandatory; When assigning a reservation back to the customer, all fields are required) ➡️ postpone

We need to identify:

- Is there a bundle available that solves this?
- If not, do we implement this in CUBE Common Bundle?

**Comment by SimonHeimberg** [comment]
WIP (Work In Progress)

---

question: how should the mapping look like?
 * One doctrineField for all dynamicFields of an entity, type array
 * One table for each EntityClass with dynamicFields, columns {entityId, fieldName, fieldType, fieldValue, fieldData}
 * One table for all EntityClasses , columns {entityType, entityId, fieldName, fieldType, fieldValue, fieldData}

I will probably recommend to realize this in its own bundle, since it will become big and complicated.

various links:
 * https://symfony.com/doc/master/reference/configuration/doctrine.html#custom-mapping-entities-in-a-bundle


## Avaliable bundle
There for sure is no bundle fulfilling all requirements above.
some links:
* https://devhub.io/repos/LinioIT-dynamic-form-bundle defines an entire **form** in yaml (But we do not want the entire form there probably. And we probably want to limit the entities which allow custom fields.)
 * https://stackoverflow.com/questions/35869096/configurable-dynamic-doctrine-database-entities-in-symfony-2 no bundle suggested for entities

## implemented with some traits, macros, ...

### .gitignore
`/app/config/dynamic_fields.yml`

### app/config/config.yml
```yaml
imports:
    - { resource: ... }
    - { resource: dynamic_fields.yml } # this is added
...
```
### .../Entity/xxx.php:
```php
class xxx {
	use DynamicFieldsTrait; // add this line, or allow to use an annotation
	
	....
}
```
```php
### .../Form/xxxType.php:

class xxxType extends yyyType {
    createForm(xxx)
    {
        $builder->add(...);
        $dynamicFormService->addFields($builder);
    }
...
```
// or in controller
```php
$form->add(xxx, );
$dynamicFormService->addFields($form);
```

### in index.html.twig:
```twig
import dynamicFields.macro.twig as dynamicFields

...
{{ dynamicFields.showFieldsHeadings(entities) }}
...
{{ dynamicFields.showFieldsFilters(entities) }}
...
{% for(...) %}
    ...
    {{ dynamicFields.showFieldsValue(entity) }}
```

### DynamicFildsTrait.php
```php
trait DynamicFieldsTrait {
	// to "use" in Entity

	/**
	 * @ORM\.....   DoctrineArray
	 */
    private $dynamicFields;
	
    public static function listDynamicFields()
    ...	
}
```

### in Bundle

#### src/DependencyInjection/ThisBundleNameExtension.php
`// sets Configuration(.php)`

#### src/DependencyInjection/Configuration.php
`// validates and parses config`

#### ...

## config only

in short: forget about. Is complicated, almost write your own framework. And not everything can be done config only. How should it inject the columns in the index pages?

in long:
requires things to do in compiler pass https://symfony.com/doc/master/service_container/compiler_passes.html
and ... (not yet found out all)

### .gitignore
`/app/config/dynamic_fields.yml`

### app/config/config.yml
```yaml
imports:
    - { resource: ... }
    - { resource: dynamic_fields.yml } # this is added
...
dynamic_fields: # and this entire section is added
    entities: # entities allowed to configure
        Entity1: 
        Entity2: fullNameOfEntity2
```

### app/config/dynamic_fields.yml
```yaml
# contains the project specifig settings for the entities
dynamic_fields:
    config:
        Entity1:
            type: ...
            ...: ...
```

### index.html.twig
`{# same as above #}`

### in Bundle

#### src/DependencyInjection/ThisBundleNameExtension.php
`// sets Configuration(.php) and CompilerPass(.php)`

#### src/DependencyInjection/Configuration.php
`// validates and parses config`

#### src/DependencyInjection/CompilerPass.php
`// maybe extends doctrine mappings somehow`

#### ...

**Comment by MartinRosserEB** [comment]
This will be realized in https://github.com/EmchBerger/cube-custom-fields-bundle

**Comment by SimonHeimberg** [comment]
I did some tests of the cube-custom-fields-bundle on a temparary branch: https://github.com/SimonHeimberg/projectassistant/tree/testCubeCustomFieldBundle_WIP

adapt the path to the repository in composer.json
Then do ` composer install`.
While developing, I often do
```sh
mv vendor/cubetools/cube-common-fields-bundle{,~}
ln -sirT ../../path/to/the/dev/dir/of/bundle vendor/cubetools/cube-custom-fields-bundle
```
This replaces the bundle directory in vendor with a symlink to my local version I am developping on. (first moving the dir to a backup location.)
@krzysztofruszczynski @markussc

**Comment by SimonHeimberg** [comment]
hints:
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html

**Comment by SimonHeimberg** [comment]
still missing:
 * [ ] macros for index page (title may work, untested)
 * [ ] macros for show page
 
not working:
 * [ ] Fields are not saved

some more info in https://github.com/EmchBerger/projectassistant/issues/1304

**Comment by markussc** [comment]
@SimonHeimberg : took me quite some effort to understand what you have set up - amazing! Finally found a way to store the custom fields successfully. Did it for the Dossier entity, since it is more straight forward than Document. Documents still does not work, probably due to special meta data comparison during update.

**Comment by markussc** [comment]
Suggest to close this as we have our separate cube-custom-fields-bundle which works fine :)
